### ISSUE TITLE
这个库与 https://github.com/acl-dev/acl/tree/master/lib_fiber 是什么关系

### ISSUE THREAD

**Issue by missdeer** [iqiyi/libfiber#24]
看README说是一样的？

**Comment by zhengshuxin** [comment]
这个协程库是从 Acl 项目中独立出来的，二者的核心代码是一致的，libfiber 是一个独立的协程库，不必依赖 Acl，而留在 Acl 中的协程库依然需要依赖 Acl 基础模块。
