### ISSUE TITLE
 fiber_timer::start()这里是不是会内存泄露

### ISSUE THREAD

**Issue by RootYuan** [iqiyi/libfiber#26]
fiber_timer::start()函数没有保存acl_fiber_create_timer()返回的协程指针，而这个指针指向的内存是在acl_fiber_create(）里用fiber_alloc(）申请的。

所以，这块内存在fiber_timer析构后没释放吧！

修复方案就是保存指针，在timer_callback()结尾释放掉。

不知道以上想法是否正确

**Comment by zhengshuxin** [comment]
不会形成内存泄露，因为 acl_fiber_create_timer() 返回的 C 协程对象是在协程库里自动管理的，而且该对象所占空间可能还会被反复使用（内部有缓存协程对象的机制，以减少内存频繁分配释放次数）。
