### ISSUE TITLE
Mingw-w64 for Windows sup

### ISSUE THREAD

**Issue by fskoras** [iqiyi/libfiber#41]
Unless I'm mistaken and doing something wrong there is no support for building this library under Windows OS using Mingw-w64.
Would it be possible to add that support (at least for C API)?

**Comment by zhengshuxin** [comment]
Yes, the lib doesn't support MinGW on Windows OS. Using the Windows native API is a better choice.

**Comment by fskoras** [comment]
Got it! Thanks for clarifying. I'm closing the issue
