### ISSUE TITLE
有没有httpclient或者websocket client

### ISSUE THREAD

**Issue by vanehu** [iqiyi/libfiber#42]
如果支持httpclient或者wsclient 是不是应用更多一些呢

**Comment by zhengshuxin** [comment]
该库是从 acl 库( https://github.com/acl-dev/acl/ ) 独立出来的，如果你需要更多的应用功能库，可以去 https://github.com/acl-dev/acl/  去找，里面有大量的功能模块，包括 httpclient/httpserver/websocket/mqtt/redis/json/xml/db 等。
