### ISSUE TITLE
Consider fcontext_t for context switch instead of ucontext_t

### ISSUE THREAD

**Issue by nxrighthere** [iqiyi/libfiber#5]
Performance of `ucontext_t` is [not good](https://www.boost.org/doc/libs/1_69_0/libs/context/doc/html/context/performance.html) for such library. Please, consider to integrate `fcontext_t`:
https://github.com/septag/deboost.context
https://github.com/lichao2014/fcontext

**Comment by zhengshuxin** [comment]
> 
> 
> Performance of `ucontext_t` is [not good](https://www.boost.org/doc/libs/1_69_0/libs/context/doc/html/context/performance.html) for such library. Please, consider to integrate `fcontext_t`:
> https://github.com/septag/deboost.context
> https://github.com/lichao2014/fcontext

Can you write a wrap of boost's asm fiber like https://github.com/acl-dev/libfiber/blob/master/src/fiber/fiber_unix.c ?
--zsx

**Comment by nxrighthere** [comment]
I'm very busy these days, unfortunately. I can implement this when I get free time, no problem.

**Comment by xhawk18** [comment]
如果要包成和 swapcontext 类似，大概是这样。
这是我在 https://github.com/xhawk18/s_task 中的用法

`typedef void* fcontext_t;

typedef struct {
    fcontext_t  fctx;
    void* data;
} transfer_t;

typedef struct {
    fcontext_t *from;
    fcontext_t *to;
} s_jump_t;

void swap_fcontext(fcontext_t *old_fc, fcontext_t *new_fc) {
        s_jump_t jump;
        jump.from = old_fc;
        jump.to = new_fc;
        transfer_t t = jump_fcontext(new_fc, (void*)&jump);
        s_jump_t* ret = (s_jump_t*)t.data;
        *ret->from = t.fctx;
}
`

**Comment by zhengshuxin** [comment]
> ```c
> jump_fcontext
> ```

非常感谢，我试一下。

**Comment by zhengshuxin** [comment]
> 如果要将 fcontext 包成和 swapcontext 类似，大概是这样。
> 这是我在 https://github.com/xhawk18/s_task 中的用法
> 
> ```c
> typedef void* fcontext_t;
> 
> typedef struct {
>     fcontext_t  fctx;
>     void* data;
> } transfer_t;
> 
> typedef struct {
>     fcontext_t *from;
>     fcontext_t *to;
> } s_jump_t;
> 
> //这两个函数由 boost fcontext汇编代码提供
> transfer_t jump_fcontext( fcontext_t const to, void * vp);
> fcontext_t make_fcontext( void * sp, size_t size, void (* fn)( transfer_t) );
> 
> void swap_fcontext(fcontext_t *old_fc, fcontext_t *new_fc) {
>     s_jump_t jump;
>     jump.from = old_fc;
>     jump.to = new_fc;
>     transfer_t t = jump_fcontext(new_fc, (void*)&jump);
>     s_jump_t* ret = (s_jump_t*)t.data;
>     *ret->from = t.fctx;
> }
> 
> void s_task_fcontext_entry(transfer_t arg) {
>     s_jump_t* jump = (s_jump_t*)arg.data;
>     *jump->from = arg.fctx;
> 
>     //协程代码填这里
> }
> 
> //开始协程，传入栈空间和入口函数
> // make_fcontext(stack, stack_size, s_task_fcontext_entry);
> ```

非常感谢，我试一下。

**Comment by waruqi** [comment]
boost-context 的 asm 实现确实比 ucontext 快很多

**Comment by zhengshuxin** [comment]
> > 如果要将 fcontext 包成和 swapcontext 类似，大概是这样。
> > 这是我在 https://github.com/xhawk18/s_task 中的用法
> > ```c
> > typedef void* fcontext_t;
> > 
> > typedef struct {
> >     fcontext_t  fctx;
> >     void* data;
> > } transfer_t;
> > 
> > typedef struct {
> >     fcontext_t *from;
> >     fcontext_t *to;
> > } s_jump_t;
> > 
> > //这两个函数由 boost fcontext汇编代码提供
> > transfer_t jump_fcontext( fcontext_t const to, void * vp);
> > fcontext_t make_fcontext( void * sp, size_t size, void (* fn)( transfer_t) );
> > 
> > void swap_fcontext(fcontext_t *old_fc, fcontext_t *new_fc) {
> >     s_jump_t jump;
> >     jump.from = old_fc;
> >     jump.to = new_fc;
> >     transfer_t t = jump_fcontext(new_fc, (void*)&jump);
> >     s_jump_t* ret = (s_jump_t*)t.data;
> >     *ret->from = t.fctx;
> > }
> > 
> > void s_task_fcontext_entry(transfer_t arg) {
> >     s_jump_t* jump = (s_jump_t*)arg.data;
> >     *jump->from = arg.fctx;
> > 
> >     //协程代码填这里
> > }
> > 
> > //开始协程，传入栈空间和入口函数
> > // make_fcontext(stack, stack_size, s_task_fcontext_entry);
> > ```
> 
> 非常感谢，我试一下。

参照了一下您写的代码，成功将 boost 中的汇编代码移植进 libfiber 中，在对比测试上下文切换时，boost 中的性能比 libfiber 中的汇编代码略差些（可能还需要做些优化），不过通过boost coroutines汇编模块，使 libfiber 可以用在移动端的网络编程中，目前提供了可以运行在 IOS 上的网络协程示例，参见：https://github.com/iqiyi/libfiber/tree/master/samples/xcode/fiber_server 。

**Comment by zhengshuxin** [comment]
> boost-context 的 asm 实现确实比 ucontext 快很多
现在已经将 boost context asm 移植到 libfiber 中了：）
在 libfiber 中目前提供了四种上下文切换方式：ucontext swap, longjmp, asm jmp, boost jmp，对比测试了一下上下文切换性能，asm jmp 方式似乎是最快的。

**Comment by waruqi** [comment]
那可能是因为新版本boost context额外保存了浮点寄存器，之前老版本中是没有的

**Comment by zhengshuxin** [comment]
> 那可能是因为新版本boost context额外保存了浮点寄存器，之前老版本中是没有的

有可能，不过这点损耗不算多，用在移动网络通信方面应该是足够高了。
